---
dist: xenial
language: ruby
cache: bundler
addons:
  apt:
    sources:
      - augeas
    packages:
      - libaugeas-dev
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/centos:6]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=centos6
      rvm: 2.5.3
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/centos:7]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=centos7
      rvm: 2.5.3
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/debian:8]'", "bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=debian8
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/debian:9]'", "bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=debian9
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/ubuntu:16.04]'", "bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=ubuntu16.04
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/ubuntu:18.04]'", "bundle exec bolt command run 'apt-get install lsb-release gnupg iproute2 -y' --inventoryfile inventory.yaml --targets='localhost*'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=ubuntu18.04
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
  allow_failures:
    -
      before_script: ["bundle exec rake 'litmus:provision[docker, litmusimage/centos:7]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=centos7
      rvm: 2.5.3
      script: ["travis_wait 30 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
branches:
  only:
    - master
    - /^v\d/
    - /^\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "ZjmgM4a2tcCE4dtccVSmYZAcuCaXdZNsZxVzRiDg7URBYyALMNgCV6XaiS/DTHX4jCuiyw/89Vywyf+uDjrj1552D+lF3cuQMXziwJhXp9v0jJRT9kpq8CFnq4iC/qwqLj54QIhIFoVgtiY9k+2MWRoMuGveLnAmg9K6wSNvLS4="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
